language: generic
sudo: required
services:
  - docker

install: skip
script:
- tools/ci/run_all_tests.sh

# TODO(curtismuntz):
# Run all tests on branch master
# Run only changed tests on other branches
# Deploy on a release tag.

# deploy:
#   provider: script
#   script: tools/ci/deploy.sh
#   on:
#     branch: master
