language: generic
os: linux
dist: xenial
sudo: required
services:
  - docker

branches:
  except:
  - experimental

install: skip

jobs:
  include:
    - stage: test
      script: ci/travis_container_runner.sh ci/test_all.sh
    - stage: deploy
      script: ci/travis_container_runner.sh ci/deploy.sh

stages:
  - test
  - name: deploy
    if: (branch = master) AND (NOT (type IN (push, pull_request)))
