version: '2'

services:
  witness:
    image: murtis/witness_armv7hf:service
    expose:
      - 50051
      - 8000
    privileged: true
    network_mode: "host"

  # proxy:
  #   build: docker/haproxy
  #   depends_on:
  #     - witness
  #   ports:
  #     - 80:80

    #wifi-connect:
    #build: docker/wifi-connect
    #network_mode: "host"
    #privileged: true
    #labels:
    #io.resin.features.dbus: '1'
