#!/bin/bash

AMD64_TARGET=amd64
ARM_TARGET=armv7hf
AARCH64_TARGET=aarch64

build_steps(){
COMMON_STEPS="
LABEL maintainer=\"me@murt.is\"
RUN apt-get -q update && apt-get upgrade -yq && apt-get install -y \\
                      libstdc++6
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN mkdir /data
RUN ls /opt
WORKDIR /data"
}

TARGET=$AMD64_TARGET
file=Dockerfile.$TARGET
build_steps
echo "# THIS FILE WAS GENERATED BY $0. DO NOT MODIFY." > $file
echo "FROM ubuntu:bionic" >> $file
echo "$COMMON_STEPS" >> $file

TARGET=$ARM_TARGET
file=Dockerfile.$TARGET
build_steps
echo "#THIS FILE WAS GENERATED BY $0. DO NOT MODIFY." > $file
echo "FROM balenalib/armv7hf-ubuntu:bionic" >> $file
echo "RUN [ \"cross-build-start\" ]" >> $file
echo "ENV INITSYSTEM on" >> $file
echo "$COMMON_STEPS" >> $file
echo "RUN [ \"cross-build-end\" ]" >> $file

TARGET=$AARCH64_TARGET
file=Dockerfile.$TARGET
build_steps
echo "#THIS FILE WAS GENERATED BY $0. DO NOT MODIFY." > $file
echo "FROM balenalib/aarch64-ubuntu:bionic" >> $file
echo "RUN [ \"cross-build-start\" ]" >> $file
echo "ENV INITSYSTEM on" >> $file
echo "$COMMON_STEPS" >> $file
echo "RUN [ \"cross-build-end\" ]" >> $file

echo "Dockerfiles generated for $AMD64_TARGET $ARM_TARGET $AARCH64_TARGET"
