#!/bin/bash

AMD64_TARGET=amd64
ARM_TARGET=armv7hf

build_steps(){
COMMON_STEPS="
LABEL maintainer=\"me@murt.is\"
ENV INITSYSTEM on
RUN apt-get -q update && apt-get upgrade -yq
RUN apt-get -q update && \\
    apt-get install -yq --no-install-recommends \\
      build-essential \\
      python3
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN mkdir /data
RUN ls /opt
WORKDIR /data"
}

TARGET=$AMD64_TARGET
file=Dockerfile.$TARGET
build_steps
echo "# THIS FILE WAS GENERATED BY $0. DO NOT MODIFY." > $file
echo "FROM debian" >> $file
echo "$COMMON_STEPS" >> $file

TARGET=$ARM_TARGET
file=Dockerfile.$TARGET
build_steps
echo "#THIS FILE WAS GENERATED BY $0. DO NOT MODIFY." > $file
echo "FROM resin/armv7hf-debian:stretch" >> $file
echo "RUN [ \"cross-build-start\" ]" >> $file
echo "ENV INITSYSTEM on" >> $file
echo "$COMMON_STEPS" >> $file
echo "RUN [ \"cross-build-end\" ]" >> $file

echo "Dockerfiles generated for $AMD64_TARGET $ARM_TARGET"
