on: push
name: ci
jobs:
  build:
    name: "x86 build and test"
    runs-on: murtis/witness_dev:latest
    steps:
    - uses: actions/checkout@master

    - name: build
      run: bazel build //witness/...
    - name: test
      run: bazel test //witness/...

  deploy:
    name: deploy
    needs: build
    runs-on: murtis/witness_dev:latest
    strategy:
      matrix:
        architecture: ["aarch64", "armv7hf", "amd64"]
    steps:
    - name: login to registry
      env:
        docker_password: ${{ secrets.docker_password }}
      run: |
        docker login \
            -u murtis \
            -p ${docker_password}

    - name: deploy
      run: |
        bazel run \
          --host_force_python=PY2 \
          --local_ram_resources=HOST_RAM*.25 \
          --local_cpu_resources=HOST_CPUS-3 \
          --config="$1" \
          "//deploy:push_witness_$1"
