on:
  push:
    branches:
      - master
name: publish
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ["aarch64", "armv7hf", "amd64"]
    steps:
    - uses: actions/checkout@master

    - name: login to registry
      env:
        docker_password: ${{ secrets.docker_password }}
      run: |
        docker login \
            -u murtis \
            -p ${docker_password}

    - name: publish images
      uses: curtismuntz/witness/.github/actions/dev_environment@master
      with:
        args: |
          bazel run \
            --host_force_python=PY2 \
            --config=${{ matrix.architecture }} \
            //deploy:push_witness_${{ matrix.architecture }}
